### ISSUE TITLE
Suggestions for how to integrate roma into hloc?

### ISSUE THREAD

**Issue by catid** [Vincentqyw/image-matching-webui#11]
Looks like you're using the hloc codebase here.  Is your code a good example of how to integrate RoMa into hloc to improve the quality of hloc results?

**Comment by Vincentqyw** [comment]
I think yes, but I have not tried yet. I used a simplified version of hloc lib, because I don't need to do sfm or triangulation things.
Roma is a dense matcher, you can refer to [roma.py](https://github.com/Vincentqyw/image-matching-webui/blob/main/hloc/matchers/roma.py) and [match_dense](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/match_dense.py) in their original repo, and then modify the aachenv11 pipeline [here](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/pipelines/Aachen_v1_1/pipeline_loftr.py).

**Comment by catid** [comment]
Gave it a shot but didn't get good results
